name: build

on:
  workflow_dispatch:
 # push:
 #   branches:
 #     - '**'
  #  tags:
 #     - 'v*.*.*'
 # pull_request:
 #   branches:
 #     - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.actor == 'dependabot[bot]' }}

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: install docker
        uses: docker-practice/actions-setup-docker@master
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Force Rootful Native OverlayFS
        run: |-
          printf '%s\n' '#!/bin/sh' 'exec /usr/bin/sudo -n -- /usr/bin/buildah "$@"' | sudo tee /usr/local/bin/buildah
          printf '%s\n' '#!/bin/sh' 'exec /usr/bin/sudo -n -- /usr/bin/podman "$@"' | sudo tee /usr/local/bin/podman
          printf '%s\n' '#!/bin/sh' 'exec /usr/bin/sudo -n -- /usr/bin/skopeo "$@"' | sudo tee /usr/local/bin/skopeo
          sudo chmod a+x /usr/local/bin/buildah /usr/local/bin/podman /usr/local/bin/skopeo

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
        
      - name: Build
        uses: redhat-actions/buildah-build@v2
        with:
          image: docker.io/wrhsd/feedbin-one
          tags: ${{ steps.date.outputs.today }}
          platforms: linux/arm64
          labels: ${{ steps.docker-metadata.outputs.labels }}
          containerfiles: |-
            Containerfile
          extra-args: |-
            --cap-add=sys_admin,mknod
            --volume /var/run/docker.sock:/var/run/docker.sock      
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1  # 三方的action操作， 执行docker login
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # 配置dockerhub的认证，在Github项目主页 【Settings】 -> 【Secrets】 添加对应变量
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wrhsd/feedbin-one/${{ steps.date.outputs.today }}
